export const ALL_BOATS_REQUEST = 'ALL_BOATS_REQUEST'; 
export const ALL_BOATS_SUCCESS = 'ALL_BOATS_SUCCESS'; 
export const ALL_BOATS_FAIL = 'ALL_BOATS_FAIL'; 

export const BOAT_DETAILS_REQUEST = 'BOAT_DETAILS_REQUEST'; 
export const BOAT_DETAILS_SUCCESS = 'BOAT_DETAILS_SUCCESS'; 
export const BOAT_DETAILS_FAIL = 'BOAT_DETAILS_FAIL'; 

export const CLEAR_ERRORS = 'CLEAR_ERRORS'; 