export const ALL_BOATS_REQUEST = 'ALL_BOATS_REQUEST'; 
export const ALL_BOATS_SUCCESS = 'ALL_BOATS_SUCCESS'; 
export const ALL_BOATS_FAIL = 'ALL_BOATS_FAIL';

export const NEW_BOAT_REQUEST = 'NEW_BOAT_REQUEST'; 
export const NEW_BOAT_SUCCESS = 'NEW_BOAT_SUCCESS'; 
export const NEW_BOAT_RESET = 'NEW_BOAT_RESET'; 
export const NEW_BOAT_FAIL = 'NEW_BOAT_FAIL'; 

export const BOAT_DETAILS_REQUEST = 'BOAT_DETAILS_REQUEST'; 
export const BOAT_DETAILS_SUCCESS = 'BOAT_DETAILS_SUCCESS'; 
export const BOAT_DETAILS_FAIL = 'BOAT_DETAILS_FAIL'; 

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'; 
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'; 
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'; 
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'; 

export const CLEAR_ERRORS = 'CLEAR_ERRORS'; 