export const CREATE_RESERVATION_REQUEST = 'CREATE_RESERVATION_REQUEST'
export const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS'
export const CREATE_RESERVATION_FAIL = 'CREATE_RESERVATION_FAIL'

export const MY_RESERVATIONS_REQUEST = 'MY_RESERVATIONS_REQUEST'
export const MY_RESERVATIONS_SUCCESS = 'MY_RESERVATIONS_SUCCESS'
export const MY_RESERVATIONS_FAIL = 'MY_RESERVATIONS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'