export const ALL_TRIPS_REQUEST = 'ALL_TRIPS_REQUEST';
export const ALL_TRIPS_SUCCESS = 'ALL_TRIPS_SUCCESS';
export const ALL_TRIPS_FAIL = 'ALL_TRIPS_FAIL';

export const NEW_TRIP_REQUEST = 'NEW_TRIP_REQUEST'; 
export const NEW_TRIP_SUCCESS = 'NEW_TRIP_SUCCESS'; 
export const NEW_TRIP_RESET = 'NEW_TRIP_RESET'; 
export const NEW_TRIP_FAIL = 'NEW_TRIP_FAIL';

export const UPDATE_TRIP_REQUEST = 'UPDATE_TRIP_REQUEST'; 
export const UPDATE_TRIP_SUCCESS = 'UPDATE_TRIP_SUCCESS'; 
export const UPDATE_TRIP_RESET = 'UPDATE_TRIP_RESET'; 
export const UPDATE_TRIP_FAIL = 'UPDATE_TRIP_FAIL'; 

export const TRIP_DETAILS_REQUEST = 'TRIP_DETAILS_REQUEST';
export const TRIP_DETAILS_SUCCESS = 'TRIP_DETAILS_SUCCESS';
export const TRIP_DETAILS_FAIL = 'TRIP_DETAILS_FAIL';

export const NEXT_TRIPS_REQUEST = 'NEXT_TRIPS_REQUEST'
export const NEXT_TRIPS_SUCCESS = 'NEXT_TRIPS_SUCCESS'
export const NEXT_TRIPS_FAIL = 'NEXT_TRIPS_FAIL'

export const LAST_TRIPS_REQUEST = 'LAST_TRIPS_REQUEST'
export const LAST_TRIPS_SUCCESS = 'LAST_TRIPS_SUCCESS'
export const LAST_TRIPS_FAIL = 'LAST_TRIPS_FAIL'

export const NEXT_TRIPS_BY_BOAT_REQUEST = 'NEXT_TRIPS_BY_BOAT_REQUEST'
export const NEXT_TRIPS_BY_BOAT_SUCCESS = 'NEXT_TRIPS_BY_BOAT_SUCCESS'
export const NEXT_TRIPS_BY_BOAT_FAIL = 'NEXT_TRIPS_BY_BOAT_FAIL'

export const TRIPS_BY_BOAT_REQUEST = 'TRIPS_BY_BOAT_REQUEST'
export const TRIPS_BY_BOAT_SUCCESS = 'TRIPS_BY_BOAT_SUCCESS'
export const TRIPS_BY_BOAT_FAIL = 'TRIPS_BY_BOAT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS';