export const ALL_TRIPS_REQUEST = 'ALL_TRIPS_REQUEST';
export const ALL_TRIPS_SUCCESS = 'ALL_TRIPS_SUCCESS';
export const ALL_TRIPS_FAIL = 'ALL_TRIPS_FAIL';

export const TRIP_DETAILS_REQUEST = 'TRIP_DETAILS_REQUEST';
export const TRIP_DETAILS_SUCCESS = 'TRIP_DETAILS_SUCCESS';
export const TRIP_DETAILS_FAIL = 'TRIP_DETAILS_FAIL';

export const NEXT_TRIPS_REQUEST = 'NEXT_TRIPS_REQUEST'
export const NEXT_TRIPS_SUCCESS = 'NEXT_TRIPS_SUCCESS'
export const NEXT_TRIPS_FAIL = 'NEXT_TRIPS_FAIL'

export const NEXT_TRIPS_BY_BOAT_REQUEST = 'NEXT_TRIPS_BY_BOAT_REQUEST'
export const NEXT_TRIPS_BY_BOAT_SUCCESS = 'NEXT_TRIPS_BY_BOAT_SUCCESS'
export const NEXT_TRIPS_BY_BOAT_FAIL = 'NEXT_TRIPS_BY_BOAT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS';